version: "3.8"
services:
  react:
    build: ./front
    environment:
      CHOKIDAR_USEPOLLING: "true" 
      Client_ID: "34327815257-m1nqq62fjp41m8oa0pktcmnefand8rj9.apps.googleusercontent.com"
      Client_secret: "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"
    ports:
      - "3000:3000"
    volumes:
      - ./front:/app
    stdin_open: "true"
    tty: "true"  
    depends_on: 
      - express

  express:
   build: ./backend
   environment:
     CHOKIDAR_USEPOLLING: "true" 
   ports:
     - "8080:8080"
   volumes:
     - ./backend:/app